FROM pharosproduction/elixir:latest

MAINTAINER Dmytro Nasyrov <dmytro@pharosproduction.com>

ENV REFRESHED_AT=2017-08-13 \
    TERM=xterm

# Install NPM
RUN mkdir -p /opt/app && \
    chmod -R 777 /opt/app && \
    apk update && \
    apk --no-cache --update add \
      git make g++ wget curl inotify-tools \
      nodejs nodejs-current-npm && \
    npm install npm -g --no-progress && \
    update-ca-certificates --fresh && \
    rm -rf /var/cache/apk/*

ENV PATH=./node_modules/.bin:$PATH \
    HOME=/opt/app

RUN mix local.hex --force \
  && mix local.rebar --force

WORKDIR /opt/app

CMD ["/bin/sh"]