FROM pharosproduction/nodejs

MAINTAINER Pharos Production Inc. <dmytro@pharosproduction.com>

ENV REFRESHED_AT=2017-01-25 \
  LANG=en_US.UTF-8 \
  HOME=/opt/app/ \
  TERM=xterm

WORKDIR /tmp/erlang-build

RUN mkdir -p ${HOME} \
  && adduser -s /bin/sh -u 1001 -G root -h ${HOME} -S -D default \
  && chown -R 1001:0 ${HOME} \
  && echo "@edge http://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
  && apk --no-cache upgrade \
  && apk add --no-cache pcre@edge \
  && apk add --no-cache ca-certificates openssl-dev ncurses-dev unixodbc-dev zlib-dev \
  && apk add --no-cache --virtual .erlang-build git autoconf build-base perl-dev \
  && git clone -b OTP-19.3 --single-branch --depth 1 https://github.com/erlang/otp.git . \
  && export ERL_TOP=/tmp/erlang-build && \
    export PATH=$ERL_TOP/bin:$PATH && \
    export CPPFlAGS="-D_BSD_SOURCE $CPPFLAGS" \
  && ./otp_build autoconf \
  && ./configure --prefix=/usr \
      --sysconfdir=/etc \
      --mandir=/usr/share/man \
      --infodir=/usr/share/info \
      --without-javac \
      --without-wx \
      --without-debugger \
      --without-observer \
      --without-jinterface \
      --without-cosEvent\
      --without-cosEventDomain \
      --without-cosFileTransfer \
      --without-cosNotification \
      --without-cosProperty \
      --without-cosTime \
      --without-cosTransactions \
      --without-dialyzer \
      --without-et \
      --without-gs \
      --without-ic \
      --without-megaco \
      --without-orber \
      --without-percept \
      --without-typer \
      --enable-threads \
      --enable-shared-zlib \
      --enable-ssl=dynamic-ssl-lib \
      --enable-hipe \
  && make -j4 \
  && make install \
  && apk del --force .erlang-build \
  && cd $HOME \
  && rm -rf /tmp/erlang-build \
  && update-ca-certificates --fresh

WORKDIR ${HOME}

CMD ["/bin/sh"]
