FROM alpine:3.5

MAINTAINER Dmytro Nasyrov <dmytro@pharosproduction.com>

ENV REFRESHED_AT=2017-08-13 \
	TERM=xterm

RUN apk --no-cache update \
  && apk --no-cache add python py-pip py-setuptools ca-certificates groff less openssl \
  && pip --no-cache-dir install awscli \
  && rm -rf /var/cache/apk/*

RUN pip install --upgrade pip

CMD ["/bin/sh"]