FROM pharosproduction/erlang:latest

MAINTAINER Dmytro Nasyrov <dmytro@pharosproduction.com>

ENV REFRESHED_AT=2017-04-25 \
  TERM=xterm

WORKDIR /tmp/elixir-build

RUN apk add --no-cache --update --virtual .elixir-build make \
  && apk add --no-cache --update git \
  && git clone https://github.com/elixir-lang/elixir \
  && cd elixir \
  && git checkout v1.4.2 \
  && make && make install \
  && mix local.hex --force \
  && mix local.rebar --force \
  && cd $HOME \
  && rm -rf /tmp/elixir-build \
  && apk del .elixir-build

WORKDIR ${HOME}

CMD ["/bin/sh"]